name: scrapper bot

on:
  push:
    branches: 
       - main

jobs:
  send:
    runs-on: ubuntu-20.04

    steps: 
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: action/setup-python@4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r ./libraries.txt

      - name: Run webhook
        run: python ./main.py