name: scrapper bot ci

on:
  push:
    branches: 
       - main

jobs:
  send:
    runs-on: ubuntu-20.04

    steps: 
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r ./libraries.txt

      - name: access to secrets
        run: |
          echo PERSONAL_SLACK=${{secrets.KILO_SLACK}} >> .env

      - name: Run webhook
        run: python ./main.py
