name: scrapper bot

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  send:
    run-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: action/setup-python@4
        with:
          python-version: '3.10'
          cache: pip

       - name: Install dependencies
         run: |
          python -m pip install --upgrade pip
          pip install -r ./libraries.txt